{
  try {
    return rule.apply(context.getEnvironment(),context,outputContextNode);
  }
 catch (  GenerationException ex) {
    throw ex;
  }
catch (  Throwable th) {
    context.getEnvironment().getLogger().error(rule.getRuleNode(),"unexpected exception when applying rule");
    throw new GenerationFailureException(th);
  }
}
