{
  try {
    r.run();
  }
 catch (  Exception e) {
    LOG.error(e);
    return false;
  }
  return true;
}
