{
  try {
    executeTarget("testBuildException");
  }
 catch (  BuildException e) {
    return;
  }
  fail("BuildException expected.");
}
