{
  _FunctionTypes._void_P0_E1<? extends Exception> function=new MPS14653_helper.Context<Exception>().getFunction();
  try {
    function.invoke();
    Assert.fail();
  }
 catch (  Exception e) {
  }
}
